// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAyDwKw1kGw7vUtGijuICv0PraPxBoCTo',
    appId: '1:561623714938:web:a351190c39f6e4582f7fc3',
    messagingSenderId: '561623714938',
    projectId: 'my-app-3bd63',
    authDomain: 'my-app-3bd63.firebaseapp.com',
    databaseURL: 'https://my-app-3bd63-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-app-3bd63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYO3r6nFrfO9Ec07ohu6jKpi1Gq5XdSrI',
    appId: '1:561623714938:android:e5a5f87d45b718792f7fc3',
    messagingSenderId: '561623714938',
    projectId: 'my-app-3bd63',
    databaseURL: 'https://my-app-3bd63-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-app-3bd63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv_bMRr1BFbzt_IvS-DTM6m43EJZ0NJcU',
    appId: '1:561623714938:ios:23875ce0fa68d51f2f7fc3',
    messagingSenderId: '561623714938',
    projectId: 'my-app-3bd63',
    databaseURL: 'https://my-app-3bd63-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-app-3bd63.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv_bMRr1BFbzt_IvS-DTM6m43EJZ0NJcU',
    appId: '1:561623714938:ios:23875ce0fa68d51f2f7fc3',
    messagingSenderId: '561623714938',
    projectId: 'my-app-3bd63',
    databaseURL: 'https://my-app-3bd63-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-app-3bd63.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAyDwKw1kGw7vUtGijuICv0PraPxBoCTo',
    appId: '1:561623714938:web:58b9295cd923427b2f7fc3',
    messagingSenderId: '561623714938',
    projectId: 'my-app-3bd63',
    authDomain: 'my-app-3bd63.firebaseapp.com',
    databaseURL: 'https://my-app-3bd63-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-app-3bd63.firebasestorage.app',
  );

}